app/fighterweb/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# Fighterweb apps
from home.views import IndexView

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^events/', include('events.urls', namespace="events", app_name="events")),
    url(r'^profiles/', include('accounts.urls', namespace="profiles", app_name="profiles")),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {"next_page": '/'}, name="logout"),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth", app_name="auth")),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^news/', include('news.urls', namespace="news", app_name="news")),
    url(r'^contact/', include('contact.urls', namespace="contact", app_name="contact")),
    url(r'^$', IndexView.as_view(), name='index'),
)

# If on development, use django to server MEDIA_ROOT files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/news/urls.py
from django.conf.urls import patterns, url
from .views import news_from_rss


urlpatterns = patterns('', 
    url(r'^$', news_from_rss, name='news_home'),
)

app/templates/shared/.#header.html
axolote@localhost.24125

app/templates/shared/css.html
{% load staticfiles %}

<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'fighterweb/css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fighterweb/css/bootstrap-responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fighterweb/css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fighterweb/css/theme.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'fighterweb/css/fonts.css' %} ">
<link rel="stylesheet" type="text/css" href="{% static 'fighterweb/css/theme_settings.css' %}" id="theme_color">
<link rel="stylesheet" type="text/css" href="{% static 'fighterweb/css/rs-settings.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fighterweb/css/fighterweb.css' %}">

app/templates/shared/footer.html
{% load staticfiles %}

<footer>
    <div class="footer_wrapper container">
        <a href="index.html" class="logo"><img src="{% static 'fighterweb/img/logo_footer.png' %}" alt=""  width="170" height="54" class="logo_def"><img src="{% static 'fighterweb/img/retina/logo_footer.png' %}" alt="" width="170" height="54" class="logo_retina"></a>
        <div class="copyright"><span>Combat Sports Evoloution</span>&copy; 2013 The Figther Web, LLC. All Rights Reserved<hr></div>
        <div class="footer_tools">
            <div class="footer_search_block footer_tool_block">
                <a href="javascript:void(0)" class="footer_search_toggler footer_tool_toggler"></a>
                <div class="footer_search_content">
                    <form name="search_form" method="get" action="" class="search_form">
                        <input type="text" name="search_field" value="Search the Site" title="Search the Site" class="field_search">
                    </form>
                </div>
            </div><!-- .header_social_block -->                
            <div class="footer_social_block footer_tool_block toggled">
                <a href="javascript:void(0)" class="footer_social_toggler footer_tool_toggler"></a>
                <div class="footer_social_content">
                    <ul>
                        <li><a href="#" class="ico_header-facebook"></a></li>
                        <li><a href="#" class="ico_header-twitter"></a></li>

                        <li><a href="#" class="ico_header-youtube"></a></li>
                        <li><a href="#" class="ico_header-gplus"></a></li>

                    </ul>
                </div>
            </div><!-- .header_social_block -->
        </div>
    </div>
    <hr>
</footer>

app/templates/shared/head.html
{% load staticfiles %}

app/templates/shared/header.html
{% load staticfiles %}

<div class="header_wrapper container">
  <a href="{% url "index" %}" class="logo"><img src="{% static 'fighterweb/img/logo.png' %}" alt=""  width="381" height="105" class="logo_def">
    <img src="{% static 'fighterweb/img/retina/logo.png' %}" alt="" width="381" height="105" class="logo_retina">
  </a>
  <div class="slogan"><span>Combat Sports Network</span><hr></div>
  <div class="header_tools">
    <div class="header_search_block header_tool_block">
      <a href="javascript:void(0)" class="header_search_toggler header_tool_toggler"></a>
      <div class="header_search_content">
        <form name="search_form" method="get" action="" class="search_form">
          <input type="text" name="search_field" value="Search the Site" title="Search the Site" class="field_search">
        </form>
      </div>
    </div><!-- .header_social_block -->
    <div class="header_social_block header_tool_block">
      <a href="javascript:void(0)" class="header_social_toggler header_tool_toggler"></a>
      <div class="header_social_content">
        <ul>
          <li><a href="{% url "contact:index" %}" class="ico_header-facebook"></a></li>
          <li><a href="{% url "contact:index" %}" class="ico_header-twitter"></a></li>
          <li><a href="{% url "contact:index" %}" class="ico_header-youtube"></a></li>
        </ul>
      </div>
    </div><!-- .header_social_block -->


    <div class="header_cart_block toggled header_tool_block">
      <a href="javascript:void(0)" class="header_cart_toggler header_tool_toggler"></a>
      <div class="header_cart_content">
        <!-- <span class="cart_cost">$200.00</span> -->
        <!-- <span class="cart_count">1 item</span> -->
      </div>
    </div><!-- .header_cart_block -->
    
  </div>

  <div class="login-button">
    {% if user.is_authenticated %}
    <a id="login-button" href="{% url "logout" %}" class="btn shortcode_button btn_small btn_type2">Logout</a>
    {% else %}
    <a id="login-button" href="{% url "auth:login" %}" class="btn shortcode_button btn_small btn_type2">Login / Create account</a>
    {% endif %}
  </div>
  
  <div class="clear"></div>
  <nav>
    <ul class="menu">
      <li class="current-menu-parent">
        <a href="{% url 'index' %}" title="Your Here Now!">Home</a>
      </li>
      <li>
        <a href="{% url 'events:list' %}" title="Events From All Across The U.S.">Events</a>
      </li>
      <li><a href="{% url 'profiles:list_athletes' %}" title="Find Local Athletes">Athletes</a>

      </li>
      <li><a href="{% url 'news:news_home' %}" title="The Latest Combat Sports News">News</a>

      </li>
      <li><a href="javascript:void(0)" title="Find Deals on Combat Sports Items">Store</a>

      </li>
      <li><a href="/pages/about/" title="What is The Fighter Web">About</a></li>
      <li><a href="{% url "contact:index" %}" title="Questions? Get in Touch">Contacts</a>

      </li>
    </ul>
    <!-- .menu -->
  </nav>
  <div class="clear"></div>
</div><!-- .header_wrapper -->

app/templates/shared/js.html
{% load staticfiles %}
<!--[if IE 8 ]><script>
            var e = ("article,aside,figcaption,figure,footer,header,hgroup,nav,section,time").split(',');
            for (var i = 0; i < e.length; i++) {
                document.createElement(e[i]);
            }		
        </script><![endif]-->
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script src="http://code.jquery.com/ui/1.8.2/jquery-ui.js" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'fighterweb/js/jquery.themepunch.plugins.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fighterweb/js/jquery.themepunch.revolution.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fighterweb/js/jquery.onebyone.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'fighterweb/js/theme.js' %}"></script>    
<script type="text/javascript" src="{% static 'fighterweb/js/fighterweb.js' %}"></script>

app/templates/shared/login.html
{% if not user.is_authenticated %}
<div class="sidepanel widget_login">
  <h3 class="sidebar_header">User Login</h3>
  <form name="login_form" method="post" action="{% url 'auth:login' %}?next={% firstof request.path '/' %}" class="login_form">
    {% csrf_token %}
    <input type="text" name="username" value="Username or Email" title="Username or Email" class="form_field">
    <input type="password" name="password" value="Password" title="Password" class="form_field">
    <input type="submit" name="submit" class="btn_login" id="submit2" value="Login">
    <div class="forgot_password"><a href="#">Forgot Password?</a></div>
    <div class="clear"></div>
  </form>                                
</div>
{% endif %}

app/templates/shared/pre_footer.html
{% load staticfiles %}

<div class="pre_footer">
            <div class="container">
                <aside id="footer_bar" class="row">
          
                    <div class="span3">
                        <div class="sidepanel widget_about">
                            <h3 class="sidebar_header">About Us</h3>
                            <p>The Fighter Web is a group of athletes, promoters and fans passionate about combat sports and thier exposure.</p>
                            <p><span class="colored2txt">We are dedicated</span> to providing the best online resource for fans, fighters and promoters to market for free.</p>
                            <p>Our group has years of experience in cordinating, managing and being involved with all forms of combats sports.  We are <span class="colored2txt">The Fighter Web.</span></p>
                        </div>
                    </div>
                    <div class="span3">
                        <div class="sidepanel widget_flickr">
                            <h3 class="sidebar_header">Athlete Photostream</h3>
                            <div class="flickr_widget_wrapper">
                                <script src="http://www.flickr.com/badge_code_v2.gne?count=6&display=latest&size=s&layout=x&source=user&user=95624521@N04"></script>
                            </div>
                        </div><!-- .sidepanel -->                        
                    </div>
                    <div class="span3">
                        <div class="sidepanel widget_twitter">
                            <h3 class="sidebar_header">Featured Advertiser</h3>
                            <ul class="twitter_list tweet_1057"></ul>
                        </div><!-- .widget_twitter -->
                    </div>            	
                </aside>
            </div>
        </div><

app/templates/shared/slider.html
{% load staticfiles %}

<div class="search_block">
    <h3 class="title"><span class="red">Search</span> events</h3>
    <form action="#" class="search_events" method="post">
        <div class="block">
            <div class="block_title">
                <span class="red">01.</span>
                <label><input type="radio" name="search_events" value="radio" id="search_events_0">pro</label>
                <label><input type="radio" name="search_events" value="radio" id="search_events_1">amateur</label>
            </div>
        </div>
        <div class="block">
            <div class="block_title">
                <span class="red">02.</span>type of event
            </div>
            <select id="type-of-event-search">
                {% for fighter_type in fighter_types %}
                    <option value="{{ fighter_type.pk }}">{{ fighter_type.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="block">
            <div class="block_title">
                <span class="red">03.</span>location
            </div>
            <div class="location city">
                <span class="loc_title">city</span>
                <input class="form_field" name="city" type="text" value="" />
            </div>
            <div class="location state">
                <span class="loc_title">state</span>
                <select>
                    <option value="AL">Alabama</option>
                    <option value="AK">Alaska</option>
                    <option value="AZ">Arizona</option>
                    <option value="AR">Arkansas</option>
                    <option value="CA">California</option>
                    <option value="CO">Colorado</option>
                    <option value="CT">Connecticut</option>
                    <option value="DE">Delaware</option>
                    <option value="DC">District Of Columbia</option>
                    <option value="FL">Florida</option>
                    <option value="GA">Georgia</option>
                    <option value="HI">Hawaii</option>
                    <option value="ID">Idaho</option>
                    <option value="IL">Illinois</option>
                    <option value="IN">Indiana</option>
                    <option value="IA">Iowa</option>
                    <option value="KS">Kansas</option>
                    <option value="KY">Kentucky</option>
                    <option value="LA">Louisiana</option>
                    <option value="ME">Maine</option>
                    <option value="MD">Maryland</option>
                    <option value="MA">Massachusetts</option>
                    <option value="MI">Michigan</option>
                    <option value="MN">Minnesota</option>
                    <option value="MS">Mississippi</option>
                    <option value="MO">Missouri</option>
                    <option value="MT">Montana</option>
                    <option value="NE">Nebraska</option>
                    <option value="NV">Nevada</option>
                    <option value="NH">New Hampshire</option>
                    <option value="NJ">New Jersey</option>
                    <option value="NM">New Mexico</option>
                    <option value="NY">New York</option>
                    <option value="NC">North Carolina</option>
                    <option value="ND">North Dakota</option>
                    <option value="OH">Ohio</option>
                    <option value="OK">Oklahoma</option>
                    <option value="OR">Oregon</option>
                    <option value="PA">Pennsylvania</option>
                    <option value="RI">Rhode Island</option>
                    <option value="SC">South Carolina</option>
                    <option value="SD">South Dakota</option>
                    <option value="TN">Tennessee</option>
                    <option value="TX">Texas</option>
                    <option value="UT">Utah</option>
                    <option value="VT">Vermont</option>
                    <option value="VA">Virginia</option>
                    <option value="WA">Washington</option>
                    <option value="WV">West Virginia</option>
                    <option value="WI">Wisconsin</option>
                    <option value="WY">Wyoming</option>
                </select>
            </div>
            <div class="location zip_code">
                <span class="loc_title">zip code</span>
                <input class="form_field" name="zipcode" type="text" value="" />
            </div>
            <div class="clear"></div>
        </div>
        <div class="block">
            <div class="block_title">
                <span class="red">04.</span>when
            </div>
            <label class="date_wrap"><input type="text" class="datepicker_field form_field" name="date_from" /></label>
            <label class="date_wrap"><span class="date_separator">To:</span><input type="text" class="datepicker_field form_field" name="date_to" /></label>
        </div>
        <div class="block">
            <div class="block_title">
                <span class="red">05.</span><input class="submit_btn" type="button" value="submit" name="submit" />
            </div>
        </div>
    </form>

    <h3 class="title"><span class="red">Event</span> name</h3>
    <form action="#" class="event_name" method="post">
        <div class="event_name_fields">
            <div class="fleft">
                <input class="form_field" name="name" type="text" value="" id="event-name-search" />
            </div>
            <div class="fright">
                <input class="submit_btn" type="button" value="go" name="submit" />
            </div>
            <div class="clear"></div>
        </div>
    </form>
</div>

<div class="row-fluid">
    <div class="span12 module_cont module_revolution_slider module_revolution_slider rs-fullscreen_wrapper">
        <div class="rs-fullscreen">
            <div class="fullwidthbanner-container" >
                <div class="fullwidthbanner" >
                    <ul>
                        <!-- THE FIRST SLIDE -->
                        <li data-transition="slideleft" data-slotamount="1" data-masterspeed="300">
                        <img src="{% static 'fighterweb/img/slider/slide1.jpg' %}" alt=""/>
                        <!-- THE CAPTIONS OF THE FIRST SLIDE -->
                        <div class="caption sfb stb"
                            data-x="270"
                            data-y="177"
                            data-speed="600"
                            data-start="1100">

                            <img src="{% static 'fighterweb/img/slider/ls1f_img1.png' %}" alt="Image 1">
                        </div>

                        <div class="caption lfb ltb"
                            data-x="69"
                            data-y="30"
                            data-speed="600"
                            data-start="1200">
                            <img src="{% static 'fighterweb/img/slider/ls1f_img2.png' %}" alt="Image 2">
                        </div>

                        <div class="caption sft stt"
                            data-x="607"
                            data-y="56"
                            data-speed="600"
                            data-start="1300">
                            <img src="{% static 'fighterweb/img/slider/ls1f_img3.png' %}" alt="Image 3">
                        </div>

                        <div class="caption lfr ltr"
                            data-x="328"
                            data-y="90"
                            data-speed="300"
                            data-start="1400">
                            <img src="{% static 'fighterweb/img/slider/ls1f_img4.png' %}" alt="Image 4">
                        </div>

                        <div class="caption sfr str"
                            data-x="559"
                            data-y="318"
                            data-speed="600"
                            data-start="1500">
                            <img src="{% static 'fighterweb/img/slider/ls1f_img5.png' %}" alt="Image 5">
                        </div>

                        <div class="caption sfb stb"
                            data-x="652"
                            data-y="369"
                            data-speed="300"
                            data-start="1600">
                            <img src="{% static 'fighterweb/img/slider/ls1f_img6.png' %}" alt="Image 6">
                        </div>

                        <div class="caption lfb ltb"
                            data-x="-4"
                            data-y="280"
                            data-speed="300"
                            data-start="1700">
                            <img src="{% static 'fighterweb/img/slider/ls1f_img7.png' %}" alt="Image 7">
                        </div>
                        </li>

                        <!-- THE SECOND SLIDE -->
                        <li data-transition="slideright" data-slotamount="1" data-masterspeed="300">
                        <img src="{% static 'fighterweb/img/slider/slide2.jpg' %}" alt=""/>
                        <div class="caption sfb stb"
                            data-x="305"
                            data-y="59"
                            data-speed="600"
                            data-start="1100">
                            <img src="{% static 'fighterweb/img/slider/ls2_img1.png' %}" alt="Image 1">
                        </div>
                        <div class="caption sfl stl"
                            data-x="29"
                            data-y="219"
                            data-speed="600"
                            data-start="1200">
                            <img src="{% static 'fighterweb/img/slider/ls2_img2.png' %}" alt="Image 2">
                        </div>
                        <div class="caption sfl stl"
                            data-x="660"
                            data-y="287"
                            data-speed="600"
                            data-start="1300">
                            <img src="{% static 'fighterweb/img/slider/ls2_img3.png' %}" alt="Image 3">
                        </div>
                        <div class="caption sfr str"
                            data-x="887"
                            data-y="233"
                            data-speed="600"
                            data-start="1400">
                            <img src="{% static 'fighterweb/img/slider/ls2_img4.png' %}" alt="Image 4">
                        </div>
                        <div class="caption sfr str"
                            data-x="1067"
                            data-y="344"
                            data-speed="600"
                            data-start="1500">
                            <img src="{% static 'fighterweb/img/slider/ls2_img5.png' %}" alt="Image 5">
                        </div>
                        <div class="caption sft stt"
                            data-x="193"
                            data-y="118"
                            data-speed="600"
                            data-start="1600">
                            <img src="{% static 'fighterweb/img/slider/ls2_img6.png' %}" alt="Image 6">
                        </div>
                        <div class="caption sft stt"
                            data-x="30"
                            data-y="96"
                            data-speed="600"
                            data-start="1700">
                            <img src="{% static 'fighterweb/img/slider/ls2_img7.png' %}" alt="Image 7">
                        </div>
                        <div class="caption sft stt"
                            data-x="824"
                            data-y="100"
                            data-speed="400"
                            data-start="1800">
                            <img src="{% static 'fighterweb/img/slider/ls2_img8.png' %}" alt="Image 8">
                        </div>
                        <div class="caption sft stt"
                            data-x="927"
                            data-y="185"
                            data-speed="400"
                            data-start="1900">
                            <img src="{% static 'fighterweb/img/slider/ls2_img9.png' %}" alt="Image 9">
                        </div>
                        </li>
                    </ul>
                    <div class="tp-bannertimer tp-bottom"></div>
                </div>
            </div>
        </div>
    </div><!--.module_cont -->
    <div class="clear"><!-- ClearFIX --></div>
</div><!-- .row-fluid -->

app/templates/shared/stupid_sidebar.html
{% load staticfiles %}

<!-- .sidepanel -->

<div class="sidepanel widget_about">
    <h3 class="sidebar_header">About Us</h3>

    <p>The Fighter Web is a group of athletes, promoters and fans passionate about combat sports and thier exposure.</p>

    <p><span class="colored2txt">We are dedicated</span> to providing the best online resource for fans, fighters and
        promoters to market for free.</p>

    <p>Our group has years of experience in cordinating, managing and being involved with all forms of combats sports.
        We are <span class="colored2txt">The Fighter Web.</span></p>
</div>

<div class="sidepanel widget_flickr">
    <h3 class="sidebar_header">Athlete Photostream</h3>

    <div class="flickr_widget_wrapper">
        <script src="http://www.flickr.com/badge_code_v2.gne?count=6&display=latest&size=s&layout=x&source=user&user=95624521@N04"></script>
    </div>
</div><!-- .sidepanel -->
<div class="sidepanel widget_twitter">
    <h3 class="sidebar_header">Latest Tweets</h3>
    <ul class="twitter_list tweet_1057"></ul>
    <script>
        $(document).ready(function () {
            $('.tweet_1057').tweet({
                avatar_size: 0,
                count: 3,
                username: "themedev",
                template: "{text}"
            });
        });
    </script>
</div><!-- .sidepanel -->