app/accounts/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'accounts.views',
    url(r'create/$', 'create_user', name='create_user'),
    url(r'athletes/(?P<pk>\d+)/$', 'detail_athlete', name='detail_athlete'),
    url(r'promoters/(?P<pk>\d+)/$', 'detail_promoter', name='detail_promoter'),
    url(r'^athletes/$', 'list_athletes', name='list_athletes'),
    url(r'^promoters/$', 'list_promoters', name='list_promoters'),
)

app/fighterweb/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# Fighterweb apps
from home.views import IndexView

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^events/', include('events.urls', namespace="events", app_name="events")),
    url(r'^profiles/', include('accounts.urls', namespace="profiles", app_name="profiles")),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {"next_page": '/'}, name="logout"),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth", app_name="auth")),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^news/', include('news.urls', namespace="news", app_name="news")),
    url(r'^contact/', include('contact.urls', namespace="contact", app_name="contact")),
    url(r'^$', IndexView.as_view(), name='index'),
)

# If on development, use django to server MEDIA_ROOT files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/news/urls.py
from django.conf.urls import patterns, url
from .views import news_from_rss


urlpatterns = patterns('', 
    url(r'^$', news_from_rss, name='news_home'),
)

app/accounts/models.py
import time

from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField


class BaseUser(AbstractUser):

    @property
    def get_groups(self):
        """@todo: Return the groups this user belongs to.
        This to make accessing and filtering by associations easier
        probably redundant. Still thinking about it.

        """
        pass


class Promoter(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    slug = AutoSlugField(populate_from='company_name', blank=True, null=True)
    company_name = models.CharField(max_length=255, default="Independent")
    picture = models.ImageField(upload_to="promoters/%s/" % time.time())
    bio = models.TextField(blank=True, null=True)

    def __unicode__(self):
        """ Present a fight promoter by their names and company affiliation """
        return "%s %s" % (self.user.first_name, self.user.last_name)

    def get_absolute_url(self):
        """
        Guess what it does...
        """
        return reverse("profiles:detail_promoter", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "Promoter"
        verbose_name_plural = "Promoters"


class Athlete(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    slug = AutoSlugField(populate_from='nickname', blank=True, null=True)
    nickname = models.CharField(max_length=255)
    wins = models.IntegerField()
    loses = models.IntegerField()
    bio = models.TextField(blank=True, null=True)

    # Fighter image and stuff
    picture = models.ImageField(upload_to="athletes/%s/" % time.time())

    def __unicode__(self):
        """ Return full name with nickname if present """
        return '%s "%s" %s' % (self.user.first_name, self.nickname, self.user.last_name)

    def get_absolute_url(self):
        """
        Guess what it does...
        """
        return reverse("profiles:detail_athlete", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "Athlete"
        verbose_name_plural = "Athletes"

app/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model


class UserForm(forms.ModelForm):
    password1 = forms.CharField(max_length=200, required=True,
                                widget=forms.PasswordInput(), label="Password")
    password2 = forms.CharField(max_length=200, required=True,
                                widget=forms.PasswordInput(), label="Confirm password")
    class Meta:
        model = get_user_model()
        fields = ("username", "first_name",
                  "last_name", "email")

    def clean_username(self):
        """
        Does the username exist?
        """
        username = self.cleaned_data["username"]
        try:
            get_user_model().objects.get(username=username)
        except get_user_model().DoesNotExist:
            return username
        raise forms.ValidationError("Username already taken.")

    def clean_password2(self):
        """
        Check that passwords match
        """
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password2"])
        if commit:
            user.save()
        return user

app/accounts/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy
from .models import Athlete, Promoter
from .forms import UserForm


class AthleteListView(ListView):
    """
    Display athletes and stuff. Pretty neat
    """
    model = Athlete
    template_name = "accounts/list_athletes.html"


class AthleteDetailView(DetailView):
    model = Athlete
    template_name = "accounts/detail_athlete.html"


class PromoterListView(ListView):
    """
    Pretty much the same as above... but for promoters
    """
    model = Promoter
    template_name = "accounts/list_promoters.html"


class PromoterDetailView(DetailView):
    model = Promoter
    template_name = "accounts/detail_promoter.html"


class AccountCreateView(CreateView):
    model = get_user_model()
    form_class = UserForm
    template_name = "accounts/create_user.html"

    def get_success_url(self):
        return reverse_lazy("auth:login")


create_user = AccountCreateView.as_view()
list_athletes = AthleteListView.as_view()
detail_athlete = AthleteDetailView.as_view()
list_promoters = PromoterListView.as_view()
detail_promoter = PromoterDetailView.as_view()

app/templates/accounts/create_user.html
{% extends "layouts/base.html" %}
{% load staticfiles %}
{% load form_helpers %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "fighterweb/css/shop.css" %}">
    <link rel="stylesheet" href="{% static "fighterweb/css/datetimepicker.css" %}"/>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static "fighterweb/js/bootstrap-datetimepicker.min.js" %}"></script>
    <script src="{% static "fighterweb/js/events.js" %}"></script>
{% endblock %}

{% block slider %}
{% endblock slider %}

{% block content %}
    <div class="row-fluid">
    <div class="span12 module_cont module_tabs">
    <div class="shortcode_tabs">
        <div class="all_heads_cont">
            <div id="step1-tab" class="shortcode_tab_item_title it1 head1" data-open="body1">Create user</div>
        </div>
        <div class="all_body_cont">
            <div class="shortcode_tab_item_body body1 it1">
                <div class="ip">
                    {% for key, value in form.errors.items  %}
                        <div class="alert alert-error">
                            {{ key }}: {{ value }}
                        </div>
                    {% endfor %}
                    <form action="{% url "profiles:create_user" %}" method="post" accept-charset="utf-8"
                          class="form-horizontal">
                      {% csrf_token %}
                      <fieldset>
                        <legend>Create user</legend>
                        {% for field in form %}
                          <div class="control-group">
                            {{ field|add_class:"control-label" }}
                            <div class="controls">
                              {{ field }}
                            </div>
                          </div>
                        {% endfor %}
                        <div class="control-group">
                          <div class="controls">
                            <input type="submit" value="Create" class="btn btn-danger" />
                          </div>
                        </div>
                      </fieldset>
                      
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- .shortcode_tabs -->


    <script type="text/javascript">
{#        jQuery('.shortcode_tabs').each(function (index) {#}
{#            /* GET ALL HEADERS */#}
{#            var i = 1;#}
{#            jQuery('.shortcode_tab_item_title').each(function (index) {#}
{#                jQuery(this).addClass('it' + i);#}
{#                jQuery(this).attr('whatopen', 'body' + i);#}
{#                jQuery(this).addClass('head' + i);#}
{#                jQuery(this).parents('.shortcode_tabs').find('.all_heads_cont').append(this);#}
{#                i++;#}
{#            });#}
{#            /* GET ALL BODY */#}
{#            var i = 1;#}
{#            jQuery('.shortcode_tab_item_body').each(function (index) {#}
{#                jQuery(this).addClass('body' + i);#}
{#                jQuery(this).addClass('it' + i);#}
{#                jQuery(this).parents('.shortcode_tabs').find('.all_body_cont').append(this);#}
{#                i++;#}
{#            });#}
{#        });#}

        jQuery(".shortcode_tabs .all_body_cont div:first-child").addClass('active');
        jQuery('.shortcode_tabs .all_heads_cont div:first-child').addClass('active');

{#        jQuery('.shortcode_tab_item_title').live('click', function () {#}
{#            jQuery(this).parents('.shortcode_tabs').find('.shortcode_tab_item_body').removeClass('active');#}
{#            jQuery(this).parents('.shortcode_tabs').find('.shortcode_tab_item_title').removeClass('active');#}
{#            var whatopen = jQuery(this).attr('data-open');#}
{#            jQuery(this).parents('.shortcode_tabs').find('.' + whatopen).addClass('active');#}
{#            jQuery(this).addClass('active');#}
{#        });#}
    </script>
    </div>
    <!-- .module_cont -->
    </div><!-- .row-fluid -->
{% endblock content %}

app/templates/accounts/detail_athlete.html
{% extends "layouts/base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "fighterweb/css/shop.css" %}">
{% endblock %}

{% block js %}
{{ block.super }}
<script type="text/javascript" src="{% static "fighterweb/js/shop.js" %}"></script>
{% endblock js %}

{% block slider %}
{% endblock slider %}


{% block content %}
<div class="row-fluid">
  <div class="span6 module_cont">
    <div class="product_image">
      <img src="{% thumbnail athlete.picture 420x0 crop %}" alt=""/>
    </div>
  </div>
  <div class="span6 module_cont">
    <h1 class="product_title">{{ athlete }}</h1>
    <!-- <h2 class="product_price">$200 <span class="product_oldprice">$400</span></h2> -->
    <article class="description">
      {{ athlete.bio }}
    </article>
    
    <!-- <form class="cart" method="post" action=""> -->
    <!--   <div class="quantity"> -->
    <!--     <input class="minus" type="button"> -->
    <!--     <input type="text" class="input-text qty" data-max="0" data-min="1" value="1"> -->
    <!--     <input class="plus" type="button"> -->
    <!--   </div> -->
    <!--   <a href="#" class="product_add2cart">add to cart</a> -->
    <!-- </form> -->
    
    <div class="product_meta">
      <div class="sku"><span>Name: </span>{{ athlete }}.</div>
      <div class="posted_in"><span>Wins: {{ athlete.wins }}.</div>
      <div class="tagged_as"><span>Loses: {{ athlete.loses }}.</div>
    </div>
  </div>								
</div><!-- .row-fluid -->

                                    

<div class="row-fluid">
  <div class="span12 module_cont module_feature_posts">
    <h3 class="headInModule">Related Products</h3>
    <div class="featured_slider">
      <div class="carouselslider featured_posts items3" data-count="3">
        <ul class="item_list">                                                    
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product7.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>                                          
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product8.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>                                          
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product9.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product4.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>                                          
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product5.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>                                          
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product6.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="clear"></div>
    </div><!-- .featured_slider -->
  </div><!-- .module_cont -->
</div><!-- .row-fluid -->
{% endblock content %}

app/templates/accounts/detail_promoter.html
{% extends "layouts/base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "fighterweb/css/shop.css" %}">
{% endblock %}

{% block js %}
{{ block.super }}
<script type="text/javascript" src="{% static "fighterweb/js/shop.js" %}"></script>
{% endblock js %}

{% block slider %}
{% endblock slider %}

{% block content %}
<div class="row-fluid">
  <div class="span6 module_cont">
    <div class="product_image">
      <img src="{% thumbnail promoter.picture 420x0 crop %}" alt=""/>
    </div>
  </div>
  <div class="span6 module_cont">
    <h1 class="product_title">{{ promoter }}</h1>
    <!-- <h2 class="product_price">$200 <span class="product_oldprice">$400</span></h2> -->
    <article class="description">
      {{ promoter.bio }}
    </article>
    
    <!-- <form class="cart" method="post" action=""> -->
    <!--   <div class="quantity"> -->
    <!--     <input class="minus" type="button"> -->
    <!--     <input type="text" class="input-text qty" data-max="0" data-min="1" value="1"> -->
    <!--     <input class="plus" type="button"> -->
    <!--   </div> -->
    <!--   <a href="#" class="product_add2cart">add to cart</a> -->
    <!-- </form> -->
    
    <div class="product_meta">
      <div class="sku"><span>Name: </span>{{ promoter }}.</div>
      <div class="tagged_as"><span>Company: {{ promoter.company_name }}.</div>
    </div>
  </div>								
</div><!-- .row-fluid -->

<div class="row-fluid">
  <div class="span12 module_cont module_tabs">
    <div class="shortcode_tabs">
      <div class="all_heads_cont">
        <div class="shortcode_tab_item_title it1 head1 active" data-open="body1">Description</div>
        <div class="shortcode_tab_item_title it2 head2" data-open="body2">Additional Information</div>
        <div class="shortcode_tab_item_title it3 head3" data-open="body3">Reviews (2)</div>
      </div>
      <div class="all_body_cont">
        <div class="shortcode_tab_item_body body1 it1">
          <div class="ip">
            <h4>Product Description</h4>
            <p>Etiam iaculis imperdiets nibh ac viverra telluset tismod est aliquam. Pellentesquet nisi tortor, elementum vivamus. Vitae posuere eget, ornare ac quis purustin cuts sagittisegs quam, nec tristique sapien ornare ut. Pellentesque habitant. </p>
            <p>Stique acunsapien ornare ut inentum vitaert vivamus lore. Accunsapien ornare ut elementum vitaert vivamus lore.morbi tristique senectus et netus et malesuada fames ac lore turpis egestas dictumero. Lorem ipsum dolor sit amet, onsectetur dipiscsing ut adipiscinget urna eget mi, sit amet dapibuse vehicula. Dapibus just id eget amollis libero pulvinar <a href="#">lores utegetsas</a>. Per inceptos himenaeos. Fusce in est ac libero eget euismod fringilla eu in mauris vestibulum. Aenean vel leo at lorem sollicitudin venenatis ac et sem. Donec viverra, nisi at aliquam tincidunt, <a href="#">massa mi lore</a> condimentum risus, non dapibus ipsum dolor ac enim. Fusce tincidunt orci et dolor rutrum cursus eget vehicula tortor bibendum. Nam gravida, ligula eget lacinia porttitor, mauris orci sodales urna, eu tempus lorem nisl non orci.</p>
          </div>
        </div>
        <div class="shortcode_tab_item_body body2 it2">
          <div class="ip">
            <div class="attributes_wrapper">
              <h4>Additional Information</h4>
              <table class="shop_attributes">
                <tr>
                  <th>Weight</th>
                  <td>100 kg</td>
                </tr>
                <tr>
                  <th>Dimensions</th>
                  <td>200 x 70 x 80 cm</td>
                </tr>
              </table>
            </div>                 
          </div>
        </div>
        <div class="shortcode_tab_item_body body3 it3">
          <div class="ip">
            <div class="reviews_head">
              <h4>2 Reviews for Item 01. Lorem Ipsum</h4>
              <div class="stars"><span class="star4"></span></div>
            </div>
            <div class="clear"></div>
            <ul class="product_review">
              <li class="review">
                <div class="stand_review">
                  <div class="reviewava"><img class="avatar photo" width="84" height="84" src="img/avatars/avatar1.png" alt=""></div>
                  <div class="review_body">
                    <div class="review_meta">
                      <span class="author_name"><a class="url" href="#">Anna Smith</a></span>
                      <span class="date">25 apr 2019</span>
                      <span class="comments"><a href="#respond" class="comment-reply-link">Reply</a></span>
                      <div class="stars"><span class="star3"></span></div>
                    </div>
                    <p>Etiam iaculis imperdiets nibh, ac viverra telluset. Euismod aliquam. Pellentesquet nisi tortor, elementum.
                      Vitae posuere eget, ornare quis purustin lost rhoncus sagittis mattis. Vestibulum los egest tincidunt eget es molestie.</p>
                  </div>
                  <div class="clear"></div>
                </div>
              </li>
              <li class="review">
                <div class="stand_review">
                  <div class="reviewava"><img class="avatar photo" width="84" height="84" src="img/avatars/avatar2.png" alt=""></div>
                  <div class="review_body">
                    <div class="review_meta">
                      <span class="author_name"><a class="url" href="#">Anna Smith</a></span>
                      <span class="date">25 apr 2019</span>
                      <span class="comments"><a href="#respond" class="comment-reply-link">Reply</a></span>
                      <div class="stars"><span class="star5"></span></div>
                    </div>
                    <p>Etiam iaculis imperdiets nibh, ac viverra telluset. Euismod aliquam. Pellentesquet nisi tortor, elementum.
                      Vitae posuere eget, ornare quis purustin lost rhoncus sagittis mattis. Vestibulum los egest tincidunt eget es molestie.</p>
                  </div>
                  <div class="clear"></div>                                                                        
                </div>
              </li>
            </ul>
            <a href="#" class="shortcode_button btn_small btn_type1">Add Review</a>
          </div>
        </div>
      </div>
    </div><!-- .shortcode_tabs -->                             
    <script type="text/javascript">
      jQuery('.shortcode_tabs').each(function(index) {									
      /* GET ALL HEADERS */
      var i = 1;
      jQuery('.shortcode_tab_item_title').each(function(index) {
      jQuery(this).addClass('it'+i); jQuery(this).attr('whatopen', 'body'+i);
      jQuery(this).addClass('head'+i);
      jQuery(this).parents('.shortcode_tabs').find('.all_heads_cont').append(this);
      i++;
      });
      /* GET ALL BODY */
      var i = 1;
      jQuery('.shortcode_tab_item_body').each(function(index) {
      jQuery(this).addClass('body'+i);
      jQuery(this).addClass('it'+i);
      jQuery(this).parents('.shortcode_tabs').find('.all_body_cont').append(this);
      i++;
      });
      });
      jQuery('.shortcode_tabs .all_body_cont div:first-child').addClass('active');
      jQuery('.shortcode_tabs .all_heads_cont div:first-child').addClass('active');
      
      jQuery('.shortcode_tab_item_title').live('click', function(){
      jQuery(this).parents('.shortcode_tabs').find('.shortcode_tab_item_body').removeClass('active');
      jQuery(this).parents('.shortcode_tabs').find('.shortcode_tab_item_title').removeClass('active');
      var whatopen = jQuery(this).attr('data-open');
      jQuery(this).parents('.shortcode_tabs').find('.'+whatopen).addClass('active');
      jQuery(this).addClass('active');
      }); 								
    </script>                                        
  </div><!-- .module_cont -->
</div><!-- .row-fluid -->                                    

<div class="row-fluid">
  <div class="span12 module_cont module_feature_posts">
    <h3 class="headInModule">Related Products</h3>
    <div class="featured_slider">
      <div class="carouselslider featured_posts items3" data-count="3">
        <ul class="item_list">                                                    
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product7.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>                                          
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product8.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>                                          
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product9.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product4.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>                                          
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product5.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>                                          
          <li>
            <div class="item shop_list_item">
              <div class="shop_list_image">
                <img src="img/shop/products/product6.jpg" alt=""/>
              </div>
              <div class="shop_list_descr">
                <a href="javascript:void(0)" class="add2cart"></a>
                <a href="product_info.html" class="sop_list_title">Item 01. Lorem Ipsum</a>
                <div class="shop_list_price">$200.00</div>
                <div class="shop_list_oldprice">$400.00</div>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="clear"></div>
    </div><!-- .featured_slider -->
  </div><!-- .module_cont -->
</div><!-- .row-fluid -->
{% endblock content %}

app/templates/accounts/list_athletes.html
{% extends "layouts/base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "fighterweb/css/shop.css" %}">
{% endblock %}

{% block slider %}
{% endblock slider %}

{% block content %}
<div class="row-fluid">
  <div class="span12 module_cont module_text_area">
    <h1 class="headInModule">Athletes
    <a href="{% url "events:create" %}" class="shortcode_button btn_normal btn_type10" style="float: right;">Enter Athlete</a></h1>
    <hr class="content_type">
  </div>								
</div><!-- .row-fluid -->

<div class="row-fluid">
  <div class="span12 module_cont module_shop">
    <div class="module_shop_wrapper">
      {% for athlete in athlete_list %}
      <div class="shop_list_item">
        <div class="shop_list_image">
          <img src="{% thumbnail athlete.picture 270x175 crop %}" alt=""/>
        </div>
        <div class="shop_list_descr">
          
          <a href="{{ athlete.get_absolute_url }}" class="sop_list_title">{{ athlete }}</a>
        </div>
      </div><!-- .shop_list_item -->
      {% endfor %}
      <div class="clear"></div>
    </div><!-- .module_shop_wrapper -->
    <div class="shop_filter_price">
      <select id="filter_price">
        <option>Amateur</option>
        <option>Pro</option>
        
      </select>
    </div>
    
  </div>
</div><!-- .row-fluid -->
{% endblock content %}

app/templates/accounts/list_promoters.html
{% extends "layouts/base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block css %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "fighterweb/css/shop.css" %}">
{% endblock %}

{% block slider %}
{% endblock slider %}

{% block content %}

  <div class="row-fluid">
    <div class="span12 module_cont module_text_area">
      <h1 class="headInModule">Promoters</h1>
      <hr class="content_type">
    </div>
  </div><!-- .row-fluid -->

  <div class="row-fluid">
    <div class="span12 module_cont module_shop">
      <div class="module_shop_wrapper">
        {% for promoter in promoter_list %}
          <div class="shop_list_item">
            <div class="shop_list_image">
              <img src="{% thumbnail promoter.picture 270x175 crop %}" alt=""/>
            </div>
            <div class="shop_list_descr">
              <a href="javascript:void(0)" class="add2cart"></a>
              <a href="{{ promoter.get_absolute_url }}" class="sop_list_title">{{ promoter }}</a>
            </div>
          </div><!-- .shop_list_item -->
        {% endfor %}
        <div class="clear"></div>
      </div><!-- .module_shop_wrapper -->
      <div class="shop_filter_price">
        <select id="filter_price">
          <option>Sort by Price</option>
          <option>Sort by Name</option>
          <option>Sort by Rate</option>
        </select>
      </div>
      <div class="shop_filter_older">
        <a href="#" class="shortcode_button btn_small btn_type1">Older</a>
      </div>
    </div>
  </div><!-- .row-fluid -->
{% endblock content %}