app/events/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('events.views',
    url(r'^$', 'list_event', name='list'),
    url(r'^create/$', 'create_event', name='create'),
    url(r'^addtickets/(?P<slug>[\w-]+)/$', 'add_tickets_to_event', name='add_tickets'),
    url(r'^addshows/(?P<slug>[\w-]+)/$', 'add_shows_to_event', name='add_shows'),
    url(r'^(?P<slug>[\w-]+)/shop/$', 'shop_event', name='shop'),
    url(r'^(?P<slug>[\w-]+)/$', 'detail_event', name='detail'),
)

app/fighterweb/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# Fighterweb apps
from home.views import IndexView

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^events/', include('events.urls', namespace="events", app_name="events")),
    url(r'^profiles/', include('accounts.urls', namespace="profiles", app_name="profiles")),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {"next_page": '/'}, name="logout"),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth", app_name="auth")),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^news/', include('news.urls', namespace="news", app_name="news")),
    url(r'^contact/', include('contact.urls', namespace="contact", app_name="contact")),
    url(r'^$', IndexView.as_view(), name='index'),
)

# If on development, use django to server MEDIA_ROOT files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/news/urls.py
from django.conf.urls import patterns, url
from .views import news_from_rss


urlpatterns = patterns('', 
    url(r'^$', news_from_rss, name='news_home'),
)

app/events/models.py
import time
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.gis.db import models as geomodels
from django.db.models import Min, Max
from django.template.loader import get_template
from django.template import Context
from django_extensions.db.fields import AutoSlugField
from localflavor.us.us_states import STATE_CHOICES


class Event(models.Model):
    SEATING_CHOICES = (
        (u'Open seating venue', u'Open seating venue',),
        (u'Has reserved seating', u'Has reserved seating',),
    )
    SERVICE_FEES = (
        (u'I will pay service fees', u'I will pay service fees'),
        (u'Split service fees', u'Split service fees'),
        (u'Add services fees to ticket price', u'Add service fees to ticket price'),
    )
    TICKETING_CHOICES = (
        (u'No tickets required', u'No tickets required'),
        (u'Tickets required', u'Tickets required'),
    )

    promoter = models.ForeignKey('accounts.Promoter', blank=True, null=True)
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='name', blank=True, null=True)
    starts = models.DateTimeField()
    description = models.TextField()
    short_description = models.CharField(max_length=140)
    seating = models.CharField(choices=SEATING_CHOICES, max_length=140)

    # Geographic information
    zip_code = models.IntegerField(max_length=10)
    venue = models.CharField(max_length=100)
    state = models.CharField(max_length=100, choices=STATE_CHOICES)
    city = models.CharField(max_length=100)
    point = geomodels.PointField(blank=True, null=True)

    # Fullfillment options
    ticketing = models.CharField(choices=TICKETING_CHOICES, max_length=100,
                                 blank=True, null=True)

    service_fees = models.CharField(choices=SERVICE_FEES, max_length=100,
                                    blank=True, null=True)

    # Display options
    is_published = models.BooleanField(default=False)

    # There will be a multistep form to enter events
    # Set this to true once all steps were completed
    is_complete = models.BooleanField(default=False)

    # Well.. if this event is in the past, set to True and archive
    has_ended = models.BooleanField(default=False)

    # Cover photo
    picture = models.ImageField(upload_to="events/%s/" % time.time(), blank=True, null=True)

    objects = geomodels.GeoManager()

    # def __unicode__(self):
    #     return u"%s presents %s" % (self.promoter.company_name, self.name)

    def get_absolute_url(self):
        return reverse("events:detail", kwargs={"slug": self.slug})

    def get_shop_url(self):
        return reverse("events:shop", kwargs={"slug": self.slug})


    # def get_lowest_price(self):
    #     """
    #     TODO: Do a one to one relationship. Will reduce a step here
    #     Get's the lowest price from an event by searching ticket
    #     variants
    #     """
    #     ticket = self.ticket_set.all()[0]
    #     lowest = ticket.ticketvariant_set.aggregate(lowest=Min("price"))["lowest"]
    #     return u"$%s" % lowest

    # def get_highest_price(self):
    #     """
    #     TODO: Do a one to one relationship. Will reduce a step here
    #     Get's the lowest price from an event by searching ticket
    #     variants
    #     """
    #     ticket = self.ticket_set.all()[0]
    #     highest = ticket.ticketvariant_set.aggregate(highest=Max("price"))["highest"]
    #     return u"$%s" % highest


class FightType(models.Model):
    """ What kind of fight is this? """
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return u'%s' % self.name


class Fight(models.Model):
    """ A show that contains fighters """
    LEVEL_CHOICES = (
        ("Professional", "Professional"),
        ("Amateur", "Amateur"),
    )
    fight_type = models.ForeignKey('FightType')
    event = models.ForeignKey('Event')
    level = models.CharField(max_length=100, choices=LEVEL_CHOICES)
    home = models.ForeignKey('accounts.Athlete', related_name="home")
    away = models.ForeignKey('accounts.Athlete', related_name="away")
    starts_at = models.TimeField()
    ends_at = models.TimeField()

    @property
    def duration(self):
        """
        How long will this fight take?
        """
        return str(self.ends - self.starts)

    def display(self):
        """
        Overriding the method thing.. Render a template with the
        fighters
        """
        context = {"home": self.home, "away": self.away}
        template = get_template("events/widgets/fight.html")
        return template.render(Context(context))

    def __unicode__(self):
        return u"%s" % (str(self.home) + "vs." + str(self.away))

app/events/forms.py
from django import forms
from .models import Fight, Event

class FightForm(forms.ModelForm):
    """
    This form will need some mods. There are fields
    that shouldn't be displayed, event though they need
    to be modified
    """

    class Meta:
        model = Fight
        exclude = ("event",)


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = (
            'promoter',
        )


class EventAddTicketForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ("ticketing", "service_fees",)

app/events/views.py
# Django imports
import json
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.generic import ListView, DetailView, CreateView

# Fighterweb imports
from events.forms import EventAddTicketForm, FightForm
from .models import Event, FightType, Fight
from .forms import EventForm
from stores.forms import TicketVariantForm
from stores.models import Ticket, TicketVariant


class EventListView(ListView):
    """ Display events by various parameters """
    model = Event
    template_name = "events/list.html"

    def get_context_data(self, *args, **kwargs):
        context = super(EventListView, self).get_context_data(*args, **kwargs)
        # Get what fighttypes are available
        context["fight_types"] = FightType.objects.filter(
            fight__event__in=context["object_list"]
        )
        return context


class EventDetailView(DetailView):
    model = Event
    template_name = "events/detail.html"


class EventShopView(DetailView):
    model = Event
    template_name = "events/shop.html"


class EventCreateView(CreateView):
    model = Event
    form_class = EventForm
    template_name = "events/create.html"

    def get_success_url(self):
        # Pass the created event as a get parameter for subsecuent steps
        return reverse_lazy('events:add_tickets', kwargs={"slug": self.object.slug})


def __get_master_ticket(event):
    # Get the event master ticket.. or create it if non existant
    try:
        ticket = Ticket.objects.get(event=event)
    except Ticket.DoesNotExist:
        ticket = Ticket(event=event, name=event.name,
                        slug=event.slug, description=event.description)
        ticket.save()

    return ticket


def ajax_return_ticket_form(request, slug=None):
    if not slug:
        raise Http404

    event = Event.objects.get(slug=slug)
    ticket = __get_master_ticket(event)

    # Now render the damn form


def add_tickets_to_event(request, slug):
    """
    On get request, render the template loaded with
    the just created event thing there. On an ajax
    post request create tickets relevant to said event
    :param request:
    :param slug:
    """

    event = get_object_or_404(Event, slug=slug)
    ticket = __get_master_ticket(event)

    if request.is_ajax():
        ticket_form = TicketVariantForm(request.POST, instance=TicketVariant(ticket=ticket))
        if ticket_form.is_valid():
            ticket_form.save()
            return HttpResponse(json.dumps({"status": True, "message": "Success"}), mimetype="application/json")
        else:
            # Actually return meaningfull errors
            return HttpResponse(json.dumps({"status": False, "message": "Error"}), mimetype="application/json")

    if request.method == "POST":
        # Todo: Make it work without JS... Not sure why though...
        # I'll have to remove everything ticket related from here
        # Ticket creation will only be through JS
        event_form = EventAddTicketForm(request.POST, instance=event)
        if event_form.is_valid():
            event_form.save()
            return HttpResponseRedirect(reverse("events:add_shows", kwargs={"slug": event.slug}))
    else:
        event_form = EventAddTicketForm(instance=event)
        ticket_form = TicketVariantForm(instance=TicketVariant(ticket=ticket))

    # Get the ticket model form
    return render_to_response("events/addtickets.html",
                              RequestContext(request, {"event_form": event_form,
                                                       "ticket_form": ticket_form,
                                                       "event": event}))


def add_shows_to_event(request, slug):
    event = get_object_or_404(Event, slug=slug)

    if request.is_ajax():
        fight_form = FightForm(request.POST, instance=Fight(event=event))
        messages = {"status": False, "message": "Error"}
        if fight_form.is_valid():
            fight_form.save()
            messages["status"] = True
            messages["message"] = "Success"

        return HttpResponse(json.dumps(messages), mimetype="application/json")
    else:
        fight_form = FightForm(instance=Fight(event=event))

    return render_to_response("events/shows.html",
                              RequestContext(request, {"fight_form": fight_form, "event": event}))


list_event = EventListView.as_view()
create_event = EventCreateView.as_view()
shop_event = EventShopView.as_view()
detail_event = EventDetailView.as_view()

app/templates/events/addtickets.html
{% extends "layouts/base.html" %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "fighterweb/css/shop.css" %}">
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#id_ticketing").change(function(){
                // Show form if the correct option is selected
                if ($("#id_ticketing").val() === "Tickets required") {
                    $("#ticket-form-space").removeClass("hidden");
                } else {
                    $("#ticket-form-space").addClass("hidden");
                }
            });

            if ($("#id_ticketing").val() === "Tickets required") {
                $("#ticket-form-space").removeClass("hidden");
            }

            $("#ticket-form-trigger").click(function(e){
                e.preventDefault();
                //serialize
                var data = $("#add-tickets-form").formSerialize();
                // get url
                var url = $("#ticket-form-trigger").data("url");
                console.log(data);

                $.post(url, data, function(data){
                    console.log(data);
                    $("#ticket-form-space").prepend("<div class='alert alert-success'>Ticket " + $("#id_seating").val() + " succesfully added</div>");
                    $("#add-tickets-form").resetForm();
                });
            });

        });
    </script>
{% endblock %}

{% block slider %}
{% endblock slider %}

{% block content %}
    <div class="row-fluid">
    <div class="span12 module_cont module_tabs">
    <h3 class="headInModule"><a name="anchor10"></a>Create new event</h3>

    <div class="shortcode_tabs">
        <div class="all_heads_cont">
            <div class="shortcode_tab_item_title it1 head1" data-open="body1">Step 1 (Event information)</div>
            <div class="shortcode_tab_item_title it2 head2 active" data-open="body2">Step 2 (Ticket information)</div>
            <div class="shortcode_tab_item_title it3 head3" data-open="body3">Step 3 (Shows)</div>
{#            <div class="shortcode_tab_item_title it4 head4" data-open="body4">Step 4 (Attachments)</div>#}
        </div>
        <div class="all_body_cont">
            <div class="shortcode_tab_item_body body1 it1">
                <div class="ip">

                    <form action="#" method="post" accept-charset="utf-8"
                          class="form-horizontal">
                        <fieldset>
                            <legend>Information</legend>
                            <div class="control-group">
                                <label class="control-label" for="title_id">Title</label>

                                <div class="controls">
                                    <input type="text" placeholder="Please enter your event's title"
                                           id="title_id" class=""/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label" for="shortdescription_id">Short description</label>

                                <div class="controls">
                                    <input type="text" placeholder="Please enter a brief description about the event"
                                           id="shortdescription_id" class=""/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="description_id">Description</label>

                                <div class="controls">
                                    <textarea id="description_id" name="" cols="30" rows="10" class=""
                                              placeholder="Full event description">
                                    </textarea>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend>Date and Time</legend>
                            <div class="control-group">
                                <label class="control-label" for="starton_id">Event date and time</label>

                                <div class="controls">
                                    <input type="text" placeholder="Please select a date from the dropdown"
                                           id="starton_id" class=""/>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend>Venue Information</legend>
                            <div class="control-group">
                                <label class="control-label" for="">Type of seating</label>
                                <div class="controls">
                                    <label class="radio" for="">
                                        <input type="radio" name="seating">
                                        Open seating venue
                                    </label>
                                    <label class="radio" for="">
                                        <input type="radio" name="seating">
                                        Has reserved seating
                                    </label>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="venue_id">Venue location</label>

                                <div class="controls">
                                    <input type="text" placeholder="Enter venue name"/>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend>Attendance Rules</legend>
                            <div class="control-group">
                                <div class="controls">
                                    <label class="checkbox">
                                        Allow anyone to view and attend this event?
                                        <input type="checkbox">
                                    </label>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
            <div class="shortcode_tab_item_body body2 it2">
                <div class="ip">
                    {% if event_form.non_field_errors %}
                        <div class="alert alert-error">
                            {{ event_form.non_field_errors }}
                        </div>
                    {% endif %}

                    {% if ticket_form.non_field_errors %}
                        <div class="alert alert-error">
                            {{ ticket_form.non_field_errors }}
                        </div>
                    {% endif %}
                    <form action="{% url "events:add_tickets" slug=event.slug %}" method="post" accept-charset="utf-8" class="form-horizontal" id="add-tickets-form">
                        {% csrf_token %}
                        <fieldset>
                            <legend>Ticketing option</legend>
                            <div class="control-group">
                                {% if event_form.ticketing.errors %}
                                    <div class="alert alert-error">
                                        {{ event_form.ticketing.errors }}
                                    </div>
                                {% endif %}
                                <label class="control-label" for="">
                                    Prerequisites
                                </label>
                                <div class="controls">
                                    {{ event_form.ticketing }}
                                </div>
                            </div>
                        </fieldset>

                        <fieldset id="ticket-form-space" class="hidden">
                            {% with ticket_form as ticket_form %}
                                {% include "events/widgets/ticket_form.html" %}
                            {% endwith %}
                        </fieldset>

                        <fieldset>
                            <legend>Online sales preferences</legend>
                            <div class="control-group">
                                {% if event_form.service_fees.errors %}
                                    <div class="alert alert-error">
                                        {{ event_form.service_fees.errors }}
                                    </div>
                                {% endif %}
                                <label class="control-label">Fighterweb service fees</label>

                                <div class="controls">
                                    {{ event_form.service_fees }}
                                </div>
                            </div>
                        </fieldset>
                    <input type="submit" value="Next >>" class="btn btn-danger wizard-button" />

                    </form>
                </div>
            </div>
            <div class="shortcode_tab_item_body body3 it3">
                <div class="ip">
                    <p>Accumsan in fuerat est amet consensit cellula filia navem auditum ait. Ingens ferro conparuit de
                        me missam ne velocitate renovasti dolorum Reflexio mihi. Genere sufficit puella ut casus homini
                        tamen ait. Atque ut sua coniuge sancta mihi esse deprecor possit scits quas praesent. Cras
                        porttitor porttitor turpis, eget tempus urna posuere nec. Fusce egestas nibh at neque
                        scelerisque vel pulvinar nisi gravida. Integer tincidunt tincidunt velit eu egestas. Vestibulum
                        lore cursus ipsum vitae ante luctus volutpat.</p>
                </div>
            </div>
            <div class="shortcode_tab_item_body body4 it4">
                <div class="ip">
                    <form action="#" method="post" accept-charset="utf-8" class="form-horizontal">
                        <fieldset>
                            <legend>Cover picture</legend>
                            <div class="control-group">
                                <label class="control-label" for="title_id">Upload picture</label>

                                <div class="controls">
                                    <input type="file" placeholder="Please enter your event's title"
                                           id="title_id" class=""/>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- .shortcode_tabs -->


    <script type="text/javascript">
{#        jQuery('.shortcode_tabs').each(function (index) {#}
{#            /* GET ALL HEADERS */#}
{#            var i = 1;#}
{#            jQuery('.shortcode_tab_item_title').each(function (index) {#}
{#                jQuery(this).addClass('it' + i);#}
{#                jQuery(this).attr('whatopen', 'body' + i);#}
{#                jQuery(this).addClass('head' + i);#}
{#                jQuery(this).parents('.shortcode_tabs').find('.all_heads_cont').append(this);#}
{#                i++;#}
{#            });#}
{#            /* GET ALL BODY */#}
{#            var i = 1;#}
{#            jQuery('.shortcode_tab_item_body').each(function (index) {#}
{#                jQuery(this).addClass('body' + i);#}
{#                jQuery(this).addClass('it' + i);#}
{#                jQuery(this).parents('.shortcode_tabs').find('.all_body_cont').append(this);#}
{#                i++;#}
{#            });#}
{#        });#}

        jQuery(".shortcode_tabs .all_body_cont div:nth-child(2)").addClass('active');
        jQuery('.shortcode_tabs .all_heads_cont div:nth-child(2)').addClass('active');

{#        jQuery('.shortcode_tab_item_title').live('click', function () {#}
{#            jQuery(this).parents('.shortcode_tabs').find('.shortcode_tab_item_body').removeClass('active');#}
{#            jQuery(this).parents('.shortcode_tabs').find('.shortcode_tab_item_title').removeClass('active');#}
{#            var whatopen = jQuery(this).attr('data-open');#}
{#            jQuery(this).parents('.shortcode_tabs').find('.' + whatopen).addClass('active');#}
{#            jQuery(this).addClass('active');#}
{#        });#}
    </script>
    </div>
    <!-- .module_cont -->
    </div><!-- .row-fluid -->
{% endblock content %}

app/templates/events/detail.html
{% extends "layouts/base_nosidebar.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block slider %}
{% endblock slider %}

{% block content %}
 <div class="row-fluid">
   <div class="span12 module_cont module_text_area">
     <div class="row-fluid">
       <div class="span9">
         <img src="{% thumbnail event.picture 840x0 crop %}" class="" alt="" />
       </div>
       <div class="span3 hero-unit">
         <ul>
             <li>{{ event.name }}</li>
             <li>{{ event.venue }}</li>
             <li>{{ event.starts }}</li>
         </ul>
       </div>
     </div>
   </div>								
 </div><!-- .row-fluid -->

 <div class="row-fluid">                                
   <div class="span12 module_cont module_promo_text">
     <div class="shortcode_promoblock ">
       <div class="row-fluid">
         <div class="span6 promo_text_block">
           <h1>{{ event.name }}</h1>
           <h4>{{ event.description|truncatewords:"11" }}</h4>
         </div>
         <div class="span6 promo_button_block">
           <a href="{{ event.get_shop_url }}" class="shortcode_button btn_large btn_type1 purchase_tickets">Purchase Tickets!</a>
         </div>
       </div>
     </div>
   </div><!--.module_cont -->
   <div class="clear"><!-- ClearFIX --></div>                                                                    
 </div><!-- .row-fluid -->

 <div class="row-fluid">
   <div class="span12">
     <div class="row-fluid">
     <ul class="fightcards">
     {% for fight in event.fight_set.all %}
     <li class="span6">
         {{ fight.display }}
     </li>
     {% endfor %}
     </ul>
     </div>
   </div>
 </div>

 <div class="row-fluid">
 </div><!-- .row-fluid --> 
</div>
{% endblock content %}

app/templates/events/list.html
{% extends "layouts/base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block css %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "fighterweb/css/shop.css" %}">
{% endblock %}

{% block slider %}
{% endblock slider %}

{% block content %}

  <div class="row-fluid">
    <div class="span12 module_cont module_text_area">
      <h1 class="headInModule">
        Events
        {% if request.user.is_authenticated %}


        <a href="{% url "events:create" %}" class="shortcode_button btn_normal btn_type10" style="float: right;">Create Event</a>

        {% endif %}
      </h1>
      <hr class="content_type">
    </div>
  </div><!-- .row-fluid -->

  <div class="row-fluid">
    <div class="span12 module_cont module_shop">

      <div class="module_shop_wrapper">
        {% for event in event_list %}
          <div class="shop_list_item">
            <div class="shop_list_image">
              {% if event.picture %}
                <img src="{% thumbnail event.picture 270x175 crop %}" alt=""/>
              {% else %}
                <img src="#" alt=""/>
              {% endif %}
            </div>
            <div class="shop_list_descr">
              <a href="javascript:void(0)" class="add2cart"></a>
              <a href="{{ event.get_absolute_url }}" class="sop_list_title">{{ event.name }}</a>

              <div class="shop_list_price">Starting from {{ event.get_lowest_price }}</div>
            </div>
          </div><!-- .shop_list_item -->
        {% endfor %}
        <div class="clear"></div>
      </div><!-- .module_shop_wrapper -->

    </div>
  </div><!-- .row-fluid -->
{% endblock content %}